### ISSUE TITLE
GDBM install failing

### ISSUE THREAD

**Issue by MrL1605** [tokuhirom/node-gdbm#4]
Hi
I tried to install gdbm on my machine, and I have been getting following error.
Would be pleased if you could look into it. I would have fixed myself if it were not in C.
It seems `make` command fails.

Env details:
node -v9.4.0
npm  -v6.0.0

I think gcc is also related, following is output of `gcc --version`
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
 
Following is just a part of whole stacktrace.
```
/home/aditya/.node-gyp/9.4.0/include/node/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/aditya/.node-gyp/9.4.0/include/node/v8.h:875:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../gdbm.cc:285:17: error: within this context
     HandleScope scope;
                 ^
../gdbm.cc:297:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(v8::String::NewSymbol("gdbm_version"),
                 ^
../gdbm.cc:298:9: error: ‘New’ is not a member of ‘v8::String’
         v8::String::New(gdbm_version));
         ^
../gdbm.cc:299:17: error: ‘NewSymbol’ is not a member of ‘v8::String’
     target->Set(v8::String::NewSymbol("version"),
                 ^
../gdbm.cc:300:9: error: ‘New’ is not a member of ‘v8::String’
         v8::String::New(NODE_GDBM_VERSION));
         ^
../gdbm.cc: In static member function ‘static v8::Handle<v8::Value> GDBM::StrError(const int&)’:
../gdbm.cc:93:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
../gdbm.cc: In static member function ‘static v8::Handle<v8::Value> GDBM::Errno(const int&)’:
../gdbm.cc:271:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make: *** [Release/obj.target/gdbm/gdbm.o] Error 1
make: Leaving directory `/home/aditya/git/sweetchat/local/node_modules/gdbm/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/aditya/cx/tools/nodejs-9.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.10.0-693.21.1.el7.x86_64
gyp ERR! command "/home/aditya/cx/tools/nodejs-9.4.0/bin/node" "/home/aditya/cx/tools/nodejs-9.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aditya/git/sweetchat/local/node_modules/gdbm
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by tokuhirom** [comment]
ah, i should update the code to support latest node. please wait a moment

--
tokuhirom
